sudo: false
language: node_js
node_js:
  - '9'
cache:
  directories:
    - node_modules
services:
  - docker
before_install: npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
